// packages/react-tabs/src/Tabs.jsx
import React from 'react'
import PropTypes from 'prop-types'
import Octicon from 'octicons-react'
import { SwitchTransition, CSSTransition } from 'react-transition-group'
import classNames from 'classnames'
import { setHash, themeDefault } from '@hiendv/tabs'
import TabPanel from './TabPanel.jsx'
import Tab from './Tab.jsx'
import './assets/transitions/slide-down.scss'

export default class Tabs extends React.Component {
  constructor () {
    super()
    this.state = {
      active: 0
    }
    this.items = this.items.bind(this)
    this.syncActiveHash = this.syncActiveHash.bind(this)
    this.currentHash = this.currentHash.bind(this)
    this.isActive = this.isActive.bind(this)
    this.setHash = this.setHash.bind(this)
    this.setActive = this.setActive.bind(this)
    this.handleClick = this.handleClick.bind(this)
  }
  componentDidMount () {
    this.setActive(this.props.show)
    this.syncActiveHash()
  }
  items () {
    return this.props.children.map(c => c.props)
  }
  activePanel () {
    return this.props.children.find((panel, i) => this.isActive(i))
  }
  currentHash () {
    return (this.props.route ? this.props.route.hash : window.location.hash).substring(1)
  }
  isActive (index) {
    return this.state.active === index
  }
  setHash (index) {
    const hash = this.currentHash()
    const item = this.items()[index]
    if (hash === item.hash) {
      return
    }

    if (this.props.route && !hash && !item.hash) {
      return
    }

    if (this.props.route) {
      this.props.router.replace({ hash: item.hash })
    }

    setHash(item.hash)
  }
  syncActiveHash () {
    const hash = this.currentHash()
    const index = this.items().findIndex(el => {
      return el.hash === hash
    })

    if (index < 0) return

    this.setActive(index)
  }
  setActive (index) {
    this.setHash(index)
    this.setState({
      active: index
    })
    if (this.props.onUpdate) {
      this.props.onUpdate(index)
    }
  }
  handleClick (e, index) {
    e.preventDefault()
    const item = this.items()[index]
    if (item.onClick) {
      item.onClick(e)
    }
    if (item.ghost) {
      return
    }

    return this.setActive(index)
  }
  render () {
    const theme = this.props.theme
    return (
      <div className={classNames(this.props.className, theme.tabs)}>
        {this.props.navRenderer && this.props.navRenderer(this.items(), this)}
        {!this.props.navRenderer &&
          <nav className={theme.items}>
            {
              this.items().map(({ className, ...item }, i) => (
                <a
                  className={classNames(theme.item, {
                    [theme['item--active']]: this.isActive(i),
                    [theme['item--end']]: item.end
                  })}
                  key={i}
                  href={item.hash || '#'}
                  onClick={(e) => this.handleClick(e, i)}>
                  {item.icon.attrs() ? (
                    <React.Fragment>
                      <Octicon icon={item.icon} className={theme.octicon}/> {item.title}
                    </React.Fragment>
                  ) : item.title
                  }
                </a>
              ))
            }
          </nav>
        }
        {<SwitchTransition mode='out-in'>
          <CSSTransition
            key={this.state.active}
            addEndListener={(node, done) => node.addEventListener('transitionend', done, false)}
            classNames='slide-down'
            timeout={150}>
            <TabPanel key={this.state.active} className={classNames(theme.panel, 'slide-down')} item={this.activePanel()}></TabPanel>
          </CSSTransition>
        </SwitchTransition>}
      </div>
    )
  }
}

Tabs.propTypes = {
  theme: PropTypes.object,
  show: PropTypes.number,
  children: PropTypes.arrayOf(Tab),
  onUpdate: PropTypes.func,
  className: PropTypes.string,
  navRenderer: PropTypes.func,
  route: PropTypes.object,
  router: PropTypes.object
}

Tabs.defaultProps = {
  theme: themeDefault,
  show: 0,
  children: [],
  onUpdate: () => {},
  className: '',
  navRenderer: null
}

// packages/vue-tabs/src/Tabs.vue
<template>
  <div :class="theme.tabs">
    <slot name="nav" :items="slotProps">
      <nav :class="theme.items">
        <a
          v-for="(props, index) in slotProps" :key="index"
          :class="{
            [theme.item]: true,
            [theme['item--active']]: isActive(index),
            [theme['item--end']]: props.end
          }" :href="`#${props.hash || ''}`"
          @click.prevent="itemClicked(index)" v-on="listeners[index]"
        ><octicon v-if="props.icon.attrs()" :icon="props.icon" :className="theme.octicon"/> {{ props.title }}</a>
      </nav>
    </slot>
    <transition
      tag="div" name="slide-down"
      mode="out-in"
    >
      <tab-panel
        :key="active"
        :class="theme.panel" :children="activePanel"
      />
    </transition>
  </div>
</template>
<style lang="scss">
@import "assets/transitions/slide-down";
</style>
<script>
import { Octicon } from 'octicons-vue'
import { setHash, themeDefault } from '@hiendv/tabs'
import TabPanel from './TabPanel'
export default {
  components: { TabPanel, Octicon },
  props: {
    theme: {
      type: Object,
      default () {
        return themeDefault
      }
    },
    show: {
      type: Number,
      default: 0
    }
  },
  data () {
    return {
      active: 0,
      slots: []
    }
  },
  computed: {
    validChildren () {
      return this.slots.filter(vnode => vnode && vnode.fnOptions && vnode.fnOptions.name === 'Tab' && vnode.data)
    },
    slotProps () {
      return this.validChildren.map(vnode => vnode.data.props)
    },
    panels () {
      return this.validChildren.map(vnode => vnode.children)
    },
    listeners () {
      return this.validChildren.map(vnode => vnode.data.listeners)
    },
    activePanel () {
      return this.panels.find((panel, i) => this.isActive(i))
    }
  },
  watch: {
    show: {
      immediate: true,
      handler (val) {
        this.active = val
      }
    }
  },
  created () {
    this.loadSlots()
    this.syncActiveHash()
  },
  updated () {
    // Because $slots is not reactive we need these below lines for hot-reloading
    if (!this.$slots.default || !this.$slots.default.length) {
      return
    }

    if (this.$slots.default === this.slots) {
      // idk how but this comparison of objects just works o.O
      return
    }

    this.loadSlots()
  },
  methods: {
    currentHash () {
      return (this.$route ? this.$route.hash : window.location.hash).substring(1)
    },
    itemClicked (index) {
      const item = this.slotProps[index]
      if (item.ghost) {
        return
      }

      return this.setActive(index)
    },
    isActive (index) {
      if (index === this.active) {
        return true
      }

      return false
    },
    setHash (index) {
      const hash = this.currentHash()
      const item = this.slotProps[index]
      if (hash === item.hash) {
        return
      }

      if (this.$route && !hash && !item.hash) {
        return
      }

      if (this.$route) {
        this.$router.replace({ hash: item.hash })
        return
      }

      setHash(item.hash)
    },
    syncActiveHash () {
      const hash = this.currentHash()
      const index = this.slotProps.findIndex(element => {
        return element.hash === hash
      })

      if (index < 0) {
        return
      }

      this.setActive(index)
    },
    setActive (index) {
      this.setHash(index)
      this.active = index
      this.$emit('update:show', index)
    },
    loadSlots () {
      this.slots = this.$slots.default || []
    }
  }
}
</script>
